# Generated by Django 4.1.4 on 2022-12-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.category')),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.spending')),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='catigories',
            field=models.ManyToManyField(through='finance_app.SpendingToCategory', to='finance_app.category'),
        ),
        migrations.CreateModel(
            name='IncomeToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.category')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.income')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='catigories',
            field=models.ManyToManyField(through='finance_app.IncomeToCategory', to='finance_app.category'),
        ),
    ]
