# Generated by Django 4.1.4 on 2022-12-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_income_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spending',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
